#!/usr/bin/env python3
"""Codex adapter: keeps a Brain block in Codex's global AGENTS.md ($CODEX_HOME or ~/.codex).

Codex reads AGENTS.md at the start of every session. This writes standing instructions and a
snapshot of habits and inbox state between markers. brain_session_hook.py refreshes each session.
Everything else in the file is left alone. Brain re-runs it whenever it rebuilds INDEX.md; run it by hand too:
    python3 ~/Notes/.brain/brain_codex.py
Does nothing if Codex isn't installed (no CODEX_HOME and no ~/.codex).
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import session_start  # noqa: E402

START = "<!-- brain:start (generated by brain_codex.py; edits here are overwritten) -->"
OLD_START = "<!-- brain:start (generated by ~/Notes/.brain/codex.py; edits here are overwritten) -->"
END = "<!-- brain:end -->"


def codex_home():
    home = os.environ.get("CODEX_HOME") or os.path.expanduser("~/.codex")
    return home if os.path.isdir(home) else None


def block():
    notes = session_start.NOTES.replace(os.path.expanduser("~"), "~", 1).replace("\\", "/")
    root = os.path.dirname(os.path.abspath(__file__)).replace("\\", "/")
    command = "py" if os.name == "nt" else "python3"
    return "\n".join([
        START,
        "## Brain",
        "`%s` is my brain: plain markdown notes. Before project work, read `%s/INDEX.md` and that project's page."
        % (notes, notes),
        "Follow the `on` habits in `codex/habits.md` (they apply to you too); propose new ones there, never enable them.",
        "File inbox captures into the right note and remove them from `inbox.md`. Add to `nudges.md` only when it clearly",
        "helps, and never re-add one marked `no`. After real work, write a session note (`%s/session-template.md`)," % root,
        "update the project page and `now.md`, then run `%s %s/build.py` with `BRAIN_NOTES=%s`." % (command, root, notes),
        "",
        "Current state (refreshed automatically):",
        "```",
        session_start.context(),
        "```",
        END,
    ])


def sync(path=None):
    """Write or refresh the block. Returns the AGENTS.md path, or None when Codex isn't installed."""
    if path is None:
        home = codex_home()
        if not home or not os.path.isdir(session_start.NOTES):
            return None
        path = os.path.join(home, "AGENTS.md")
    try:
        with open(path, encoding="utf-8") as f:
            text = f.read()
    except OSError:
        text = ""
    pattern = re.compile("(?:%s|%s).*?%s" % (re.escape(START), re.escape(OLD_START), re.escape(END)), re.S)
    new = pattern.sub(lambda _: block(), text) if pattern.search(text) else (text.rstrip("\n") + "\n\n" if text.strip() else "") + block() + "\n"
    if new != text:
        with open(path + ".tmp", "w", encoding="utf-8") as f:
            f.write(new)
        os.replace(path + ".tmp", path)
    return path


if __name__ == "__main__":
    out = sync()
    print("Updated %s" % out if out else "Codex not found (no $CODEX_HOME or ~/.codex). Nothing to do.")
